Workflow to Publish Release Uploaded

diff --git a/.github/workflows/publish_release.yaml b/.github/workflows/publish_release.yaml
--- a/.github/workflows/publish_release.yaml
+++ b/.github/workflows/publish_release.yaml
@@ -9,11 +9,76 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+      - name: Install setuptools
+        run: |
+          python -m pip install --user --upgrade setuptools wheel
+      - name: Build and test source archive and wheel file
+        run: |
+          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
+          root_dir=$PWD
+          echo "$root_dir"
+          set -e
+          
+          # build tar.gz and wheel
+          python setup.py sdist bdist_wheel --build-number $(date +'%Y%m%d%H%M')
+          tmp_dir=$(mktemp -d)
+          cp dist/Hive_ML* "$tmp_dir"
+          cd "$tmp_dir"
+          ls -al
+          
+          # install from tar.gz
+          python -m pip install Hive_ML*.tar.gz
+          python -c 'import Hive_ML; print(Hive_ML.__version__) ' 2>&1 | grep -iv "unknown"
+          python -c 'import Hive_ML; print(Hive_ML.__file__)'
+          python -m pip uninstall -y Hive_ML
+          rm Hive_ML*.tar.gz
+          
+          # install from wheel
+          python -m pip install Hive_ML*.whl
+          python -c 'import Hive_ML; print(Hive_ML.__version__) ' 2>&1 | grep -iv "unknown"
+          python -c 'import Hive_ML; print(Hive_ML.__file__)'
+          
+          # clean up
+          cd "$root_dir"
+          rm -r "$tmp_dir"
+          rm -rf Hive_ML/
+          ls -al .
+      - name: Quick test installed
+        run: |
+                python -m pip install -r requirements.txt
+                # python -m tests.min_tests
+              env:
+                QUICKTEST: True
+
+      - if: startsWith(github.ref, 'refs/tags/')
+        name: Upload artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: dist
+          path: dist/
+
+      - if: startsWith(github.ref, 'refs/tags/')
+        name: Check artifacts
+        run: |
+          ls -al dist/
+          rm dist/monai*.tar.gz
+          ls -al dist/
+
+      - if: startsWith(github.ref, 'refs/tags/')
+        name: Publish to Test PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          password: ${{ secrets.PYPI_API_TOKEN }}
+          repository-url: https://test.pypi.org/legacy/
+      
+      
+
       - name: Release
         uses: softprops/action-gh-release@v1
         if: startsWith(github.ref, 'refs/tags/')
         with:
           generate_release_notes: True
+
   build-n-publish:
     name: Build and publish Python 🐍 distributions 📦 to PyPI
     runs-on: ubuntu-latest
@@ -31,15 +96,15 @@ jobs:
           pip install
           build
           --user
-      - name: Build a binary wheel and a source tarball
-        run: >-
-          python3 -m
-          build
-          --sdist
-          --wheel
-          --outdir dist/
-      - name: Publish distribution to PyPI
-        uses: pypa/gh-action-pypi-publish@release/v1
-        if: startsWith(github.ref, 'refs/tags/')
-        with:
-          password: ${{ secrets.PYPI_API_TOKEN }}
+      #- name: Build a binary wheel and a source tarball
+      #  run: >-
+      #    python3 -m
+      #    build
+      #    --sdist
+      #    --wheel
+      #    --outdir dist/
+      #- name: Publish distribution to PyPI
+      #  uses: pypa/gh-action-pypi-publish@release/v1
+      #  if: startsWith(github.ref, 'refs/tags/')
+      #  with:
+      #    password: ${{ secrets.PYPI_API_TOKEN }}
